import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Home page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <h1>Main Navbar</h1>
        {children}
      </body>
    </html>
  );
}
